### ISSUE TITLE
Max prefix limit exceed shutdown with auto recovery

### ISSUE THREAD

**Issue by nitesh058** [pierky/arouteserver#122]
Hi Pierky, could you please help with the auto-recovery time trigger to enable BGP, which got auto shutdown due to the max limit reach.
please provide any script or feature for this.

**Comment by pierky** [comment]
Hi @nitesh058, I'm not sure what you're requesting here. Have some sessions been disabled due to max-prefix limit, and then you're looking for a solution to automatically re-enable them? If that's the case, this feature is not provided in ARouteServer, it's out of scope, since ARouteServer is just a tool that can be used to configure IXP route servers, and not to perform operations or any other type of automation.

The automation you're aiming to could potentially be quite complex, depending on your environment and on the conditions (the "business logic") you would like to implement to "trigger" the auto-recovery mechanism.

If you're using the tool to configure OpenBGPD, then you can leverage the `restart_after` config setting (see https://github.com/pierky/arouteserver/blob/master/config.d/general.yml#L445-L447), that allows the tool to configure the BGP daemon with the `restart XXX` options (see https://man.openbsd.org/bgpd.conf#max-prefix). OpenBGPD supports the "auto-restart after XXX minutes" feature itself, which BIRD doesn't offer AFAIK.

Hope this clarifies the situation a bit. Going to close the ticket, feel free to re-open it if you believe there's something else to be done here.
